//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://xml.osisoft.com/services/PIDataService", ConfigurationName="IPITimeSeries")]
public interface IPITimeSeries
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xml.osisoft.com/services/IPITimeSeries/GetPIArchiveData", ReplyAction="http://xml.osisoft.com/services/IPITimeSeries/GetPIArchiveDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataItem))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIManner))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIConstraint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIDataRequest))]
    TimeSeries[] GetPIArchiveData(PIArcDataRequest[] requests);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xml.osisoft.com/services/IPITimeSeries/GetPIUpdates", ReplyAction="http://xml.osisoft.com/services/IPITimeSeries/GetPIUpdatesResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataItem))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIManner))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIConstraint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIDataRequest))]
    TimeSeriesUpdates[] GetPIUpdates(System.Guid updateTicket, ushort maxWaitForUpdates, UpdateFilterType evtFilter);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xml.osisoft.com/services/IPITimeSeries/SignUpForPIUpdates", ReplyAction="http://xml.osisoft.com/services/IPITimeSeries/SignUpForPIUpdatesResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataItem))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIManner))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIConstraint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIDataRequest))]
    SignUpResults SignUpForPIUpdates(string[] paths, ushort expiration);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xml.osisoft.com/services/IPITimeSeries/CancelSignUpForPIUpdates", ReplyAction="http://xml.osisoft.com/services/IPITimeSeries/CancelSignUpForPIUpdatesResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataItem))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIManner))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIConstraint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIDataRequest))]
    void CancelSignUpForPIUpdates(System.Guid updateTicket);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xml.osisoft.com/services/IPITimeSeries/ListPaths", ReplyAction="http://xml.osisoft.com/services/IPITimeSeries/ListPathssResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataItem))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIManner))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIConstraint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIDataRequest))]
    string[] ListPathsByUpdateTicket(System.Guid updateTicket);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xml.osisoft.com/services/IPITimeSeries/GetPISnapshotData", ReplyAction="http://xml.osisoft.com/services/IPITimeSeries/GetPISnapshotDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataItem))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIManner))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIConstraint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIDataRequest))]
    TimeSeries[] GetPISnapshotData(string[] paths);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xml.osisoft.com/services/IPITimeSeries/GetPISummaryData", ReplyAction="http://xml.osisoft.com/services/IPITimeSeries/GetPISummaryDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataItem))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIManner))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIConstraint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIDataRequest))]
    TimeSeries[] GetPISummaryData(PISummaryDataRequest[] requests);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xml.osisoft.com/services/IPITimeSeries/InsertPIData", ReplyAction="http://xml.osisoft.com/services/IPITimeSeries/InsertPIDataResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataItem))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIManner))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIConstraint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIDataRequest))]
    TimeSeries InsertPIData(TimeSeries[] events, InsertPIDataDuplicateSwitch duplicateSwitch);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://xml.osisoft.com/services/IPITimeSeries/GetProductVersion", ReplyAction="http://xml.osisoft.com/services/IPITimeSeries/GetProductVersionResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DataItem))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIManner))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIConstraint))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PIDataRequest))]
    string GetProductVersion();
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class PIArcDataRequest : PIDataRequest
{
    
    private PIArcManner pIArcMannerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public PIArcManner PIArcManner
    {
        get
        {
            return this.pIArcMannerField;
        }
        set
        {
            this.pIArcMannerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class PIArcManner : PIManner
{
    
    private PIArcMannerRetrievalType retrievalTypeField;
    
    private int numValuesField;
    
    private PIArcMannerBoundaries boundariesField;
    
    public PIArcManner()
    {
        this.retrievalTypeField = PIArcMannerRetrievalType.Compressed;
        this.numValuesField = 400;
        this.boundariesField = PIArcMannerBoundaries.Inside;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PIArcMannerRetrievalType.Compressed)]
    public PIArcMannerRetrievalType RetrievalType
    {
        get
        {
            return this.retrievalTypeField;
        }
        set
        {
            this.retrievalTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(400)]
    public int NumValues
    {
        get
        {
            return this.numValuesField;
        }
        set
        {
            this.numValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PIArcMannerBoundaries.Inside)]
    public PIArcMannerBoundaries Boundaries
    {
        get
        {
            return this.boundariesField;
        }
        set
        {
            this.boundariesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.osisoft.com/services/PIDataService")]
public enum PIArcMannerRetrievalType
{
    
    /// <remarks/>
    Compressed,
    
    /// <remarks/>
    Interpolated,
    
    /// <remarks/>
    PlotValues,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.osisoft.com/services/PIDataService")]
public enum PIArcMannerBoundaries
{
    
    /// <remarks/>
    Inside,
    
    /// <remarks/>
    Outside,
    
    /// <remarks/>
    Interpolated,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PISummaryManner))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PIArcManner))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public abstract partial class PIManner
{
    
    private string filterField;
    
    private bool updatesField;
    
    public PIManner()
    {
        this.updatesField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Filter
    {
        get
        {
            return this.filterField;
        }
        set
        {
            this.filterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool Updates
    {
        get
        {
            return this.updatesField;
        }
        set
        {
            this.updatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class SignUpResults
{
    
    private System.Guid updateTicketField;
    
    private int[] errorsField;
    
    private string[] errDescsField;
    
    private int errorCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.Guid UpdateTicket
    {
        get
        {
            return this.updateTicketField;
        }
        set
        {
            this.updateTicketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Errors", Order=1)]
    public int[] Errors
    {
        get
        {
            return this.errorsField;
        }
        set
        {
            this.errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ErrDescs", Order=2)]
    public string[] ErrDescs
    {
        get
        {
            return this.errDescsField;
        }
        set
        {
            this.errDescsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int ErrorCount
    {
        get
        {
            return this.errorCountField;
        }
        set
        {
            this.errorCountField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimedValueUpdate))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class TimedValue
{
    
    private string pathField;
    
    private string flagsField;
    
    private System.DateTime timeField;
    
    private string uOMField;
    
    private string statusField;
    
    private double pctGoodField;
    
    private bool pctGoodFieldSpecified;
    
    private string dataTypeField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Flags
    {
        get
        {
            return this.flagsField;
        }
        set
        {
            this.flagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime Time
    {
        get
        {
            return this.timeField;
        }
        set
        {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UOM
    {
        get
        {
            return this.uOMField;
        }
        set
        {
            this.uOMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double PctGood
    {
        get
        {
            return this.pctGoodField;
        }
        set
        {
            this.pctGoodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PctGoodSpecified
    {
        get
        {
            return this.pctGoodFieldSpecified;
        }
        set
        {
            this.pctGoodFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DataType
    {
        get
        {
            return this.dataTypeField;
        }
        set
        {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class TimedValueUpdate : TimedValue
{
    
    private UpdateType updateTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public UpdateType UpdateType
    {
        get
        {
            return this.updateTypeField;
        }
        set
        {
            this.updateTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public enum UpdateType
{
    
    /// <remarks/>
    Archive,
    
    /// <remarks/>
    Snapshot,
    
    /// <remarks/>
    Delete,
    
    /// <remarks/>
    Edit,
    
    /// <remarks/>
    AddNoReplace,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeSeries))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeSeriesUpdates))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public abstract partial class DataItem
{
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeSeriesUpdates))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class TimeSeries : DataItem
{
    
    private TimedValue[] timedValuesField;
    
    private string pathField;
    
    private string errDescField;
    
    private int errorField;
    
    private string seriesIDField;
    
    private string dataTypeField;
    
    private string uOMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
    public TimedValue[] TimedValues
    {
        get
        {
            return this.timedValuesField;
        }
        set
        {
            this.timedValuesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ErrDesc
    {
        get
        {
            return this.errDescField;
        }
        set
        {
            this.errDescField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Error
    {
        get
        {
            return this.errorField;
        }
        set
        {
            this.errorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SeriesID
    {
        get
        {
            return this.seriesIDField;
        }
        set
        {
            this.seriesIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DataType
    {
        get
        {
            return this.dataTypeField;
        }
        set
        {
            this.dataTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UOM
    {
        get
        {
            return this.uOMField;
        }
        set
        {
            this.uOMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class TimeSeriesUpdates : TimeSeries
{
    
    private TimedValueUpdate[] updatesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
    public TimedValueUpdate[] Updates
    {
        get
        {
            return this.updatesField;
        }
        set
        {
            this.updatesField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TimeRange))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public abstract partial class PIConstraint
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class TimeRange : PIConstraint
{
    
    private string startField;
    
    private string endField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Start
    {
        get
        {
            return this.startField;
        }
        set
        {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string End
    {
        get
        {
            return this.endField;
        }
        set
        {
            this.endField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PISummaryDataRequest))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(PIArcDataRequest))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public abstract partial class PIDataRequest
{
    
    private TimeRange timeRangeField;
    
    private string pathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public TimeRange TimeRange
    {
        get
        {
            return this.timeRangeField;
        }
        set
        {
            this.timeRangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
    public string Path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class PISummaryDataRequest : PIDataRequest
{
    
    private PISummaryManner pISummaryMannerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
    public PISummaryManner PISummaryManner
    {
        get
        {
            return this.pISummaryMannerField;
        }
        set
        {
            this.pISummaryMannerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public partial class PISummaryManner : PIManner
{
    
    private PISummaryMannerSummaryValue summaryValueField;
    
    private int intervalsField;
    
    private PISummaryMannerWeightType weightTypeField;
    
    private bool useStartField;
    
    public PISummaryManner()
    {
        this.summaryValueField = PISummaryMannerSummaryValue.Average;
        this.weightTypeField = PISummaryMannerWeightType.TimeWeighted;
        this.useStartField = false;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PISummaryMannerSummaryValue.Average)]
    public PISummaryMannerSummaryValue SummaryValue
    {
        get
        {
            return this.summaryValueField;
        }
        set
        {
            this.summaryValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Intervals
    {
        get
        {
            return this.intervalsField;
        }
        set
        {
            this.intervalsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PISummaryMannerWeightType.TimeWeighted)]
    public PISummaryMannerWeightType WeightType
    {
        get
        {
            return this.weightTypeField;
        }
        set
        {
            this.weightTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool UseStart
    {
        get
        {
            return this.useStartField;
        }
        set
        {
            this.useStartField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.osisoft.com/services/PIDataService")]
public enum PISummaryMannerSummaryValue
{
    
    /// <remarks/>
    Average,
    
    /// <remarks/>
    Minimum,
    
    /// <remarks/>
    Maximum,
    
    /// <remarks/>
    Range,
    
    /// <remarks/>
    StdDev,
    
    /// <remarks/>
    Total,
    
    /// <remarks/>
    PStdDev,
    
    /// <remarks/>
    Count,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.osisoft.com/services/PIDataService")]
public enum PISummaryMannerWeightType
{
    
    /// <remarks/>
    TimeWeighted,
    
    /// <remarks/>
    EventWeighted,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://xml.osisoft.com/services/PIDataService")]
public enum UpdateFilterType
{
    
    /// <remarks/>
    Snapshot,
    
    /// <remarks/>
    Archive,
    
    /// <remarks/>
    SnapshotAndArchive,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xml.osisoft.com/services/PIDataService")]
public enum InsertPIDataDuplicateSwitch
{
    
    /// <remarks/>
    InsertDuplicate,
    
    /// <remarks/>
    ReplaceDuplicate,
    
    /// <remarks/>
    ReplaceOnlyDuplicate,
    
    /// <remarks/>
    ErrorDuplicate,
    
    /// <remarks/>
    ErrorDuplicatesSilent,
    
    /// <remarks/>
    ReplaceOnlyDuplicatesSilent,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IPITimeSeriesChannel : IPITimeSeries, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PITimeSeriesClient : System.ServiceModel.ClientBase<IPITimeSeries>, IPITimeSeries
{
    
    public PITimeSeriesClient()
    {
    }
    
    public PITimeSeriesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public PITimeSeriesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PITimeSeriesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public PITimeSeriesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public TimeSeries[] GetPIArchiveData(PIArcDataRequest[] requests)
    {
        return base.Channel.GetPIArchiveData(requests);
    }
    
    public TimeSeriesUpdates[] GetPIUpdates(System.Guid updateTicket, ushort maxWaitForUpdates, UpdateFilterType evtFilter)
    {
        return base.Channel.GetPIUpdates(updateTicket, maxWaitForUpdates, evtFilter);
    }
    
    public SignUpResults SignUpForPIUpdates(string[] paths, ushort expiration)
    {
        return base.Channel.SignUpForPIUpdates(paths, expiration);
    }
    
    public void CancelSignUpForPIUpdates(System.Guid updateTicket)
    {
        base.Channel.CancelSignUpForPIUpdates(updateTicket);
    }
    
    public string[] ListPathsByUpdateTicket(System.Guid updateTicket)
    {
        return base.Channel.ListPathsByUpdateTicket(updateTicket);
    }
    
    public TimeSeries[] GetPISnapshotData(string[] paths)
    {
        return base.Channel.GetPISnapshotData(paths);
    }
    
    public TimeSeries[] GetPISummaryData(PISummaryDataRequest[] requests)
    {
        return base.Channel.GetPISummaryData(requests);
    }
    
    public TimeSeries InsertPIData(TimeSeries[] events, InsertPIDataDuplicateSwitch duplicateSwitch)
    {
        return base.Channel.InsertPIData(events, duplicateSwitch);
    }
    
    public string GetProductVersion()
    {
        return base.Channel.GetProductVersion();
    }
}
